apiVersion: boundary.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: boundary-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: boundary-creds
      namespace: crossplane-system
      key: credentials
