apiVersion: machine.boundary.jet.crossplane.io/v1alpha1
kind: HostCatalog
metadata:
  name: "saas-project-1"
spec:
  deletionPolicy: Delete
  forProvider:
    name: "my-host-catalog"
    scopeIdRef:
      name: saas-project-1
    type: static
  providerConfigRef:
    name: boundary-config